sudo: required
services:
  - docker
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install:
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get -y update
  - sudo apt-get install -y libsodium-dev
before_script:
  - bundle exec rake app:db:create app:db:test:prepare
script:
  - bundle exec rspec spec
env:
  - ISSUER_SEED=SDBNBVVCS6OS4VB7Z7DUETAZJUCNRYQXZQNIBZOTLE3ZX44PUUPTU2L7
  - ISSUER_ADDRESS=GCHL4DBMIBZE44WLDR6LZCPWOX72TVKXSYZ65MLOFB24FUZGQCXOXMOT
  - DISTRIBUTOR_SEED=SDBNBVVCS6OS4VB7Z7DUETAZJUCNRYQXZQNIBZOTLE3ZX44PUUPTU2L7
  - DISTRIBUTOR_ADDRESS=GAQHJNQOW2TC2QMRWH2UEZ2QIB2BDMNPOMOQPUFQ7E5CT4RYDZYRG235
  - RECIPIENT_ADDRESS=GCHL4DBMIBZE44WLDR6LZCPWOX72TVKXSYZ65MLOFB24FUZGQCXOXMOT
